version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      custom:
        ipv4_address: 172.18.0.2
    expose:
      - 5432

  web:
    container_name: "nginx"
    image: nginx:alpine
    depends_on:
      - front
    ports:
      - "8082:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      custom:
        ipv4_address: 172.18.0.3

  app:
    container_name: "app"
    image: app
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    build:
      context: .
      dockerfile: ./fastapi/Dockerfile
    ports:
      - "8000:8000"
    networks:
      custom:
        ipv4_address: 172.18.0.4
    depends_on:
      - db

  front: 
    container_name: "front"
    image: front
    build:
      context: .
      dockerfile: ./vue/Dockerfile
    ports:
      - "8080:8080"
    networks:
      custom:
        ipv4_address: 172.18.0.5
    depends_on:
      - app
    expose:
      - 8080
      
networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24

