"""init

Revision ID: e9da0fe46fea
Revises: d9f329cd7afc
Create Date: 2023-03-08 06:18:12.925907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9da0fe46fea'
down_revision = 'd9f329cd7afc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creations')
    # ### end Alembic commands ###
